---
extends:
  - eslint:recommended
  - plugin:react/recommended

settings:
  react:
    pragma: React
    version: detect
  
env:
  browser: true
  commonjs: true
  node: true
  es6: true

parser: babel-eslint

parserOptions:
  sourceType: module
  allowImportExportEverywhere: false
  codeFrame: true

rules:
  no-await-in-loop: error
  no-console: off
  curly: warn
  strict: 0
  eqeqeq: error

globals:
  DEVBUILD: readonly